// Zone classification (Step 14, AD-12). WALKING SKELETON: path patterns and a
// generated-file marker in the head 2 KB; `.gitignore` membership is covered by
// the indexer only listing non-ignored files. The evidence string is redacted and
// injection-flagged at capture.
import type { Zone } from '../stores/dao/files.js';
import { redact } from '../security/redact.js';
import { isSuspect } from '../security/injection.js';

export interface ZoneResult {
  zone: Zone;
  evidence: string | null;
  evidenceSuspect: boolean;
}

const MARKER = /(@generated|DO NOT EDIT|auto-generated|autogenerated|generated by)/i;

export function classifyZone(path: string, head: string): ZoneResult {
  const seg = path.split('/');
  const out = (zone: Zone, evidence: string | null): ZoneResult => {
    const ev = evidence === null ? null : redact(evidence).redacted;
    return { zone, evidence: ev, evidenceSuspect: ev !== null && isSuspect(ev) };
  };
  if (seg.includes('node_modules') || seg.includes('vendor')) return out('vendored', 'path segment');
  if (seg.includes('dist') || seg.includes('build')) return out('build_output', 'path segment');
  if (/(^|\/)(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|Cargo\.lock|poetry\.lock)$/.test(path)) return out('generated', 'lockfile');
  const m = MARKER.exec(head.slice(0, 2048));
  if (m !== null) {
    const line = head.slice(0, 2048).split('\n').find((l) => MARKER.test(l)) ?? m[0];
    return out('generated', line.trim().slice(0, 200));
  }
  return out('source', null);
}
